using UnityEngine;

namespace TimeCli.UnityRuntime
{
    /// <summary>
    /// Canonical click-weapon visual structure recovered from Time Clickers
    /// 1.4.5. Original mesh/texture payloads remain private and are loaded from
    /// ignored Resources generated by the public extraction tool.
    /// </summary>
    internal static class OriginalClickWeaponVisualPresentation
    {
        public const string PistolBaseMeshResource =
            "TimeCliPistolBaseAndGripMesh";
        public const string PistolChamberOneMeshResource =
            "TimeCliPistolChamberOneMesh";
        public const string PistolChamberTwoMeshResource =
            "TimeCliPistolChamberTwoMesh";
        public const string PistolTopMeshResource =
            "TimeCliPistolTopMesh";
        public const string PistolTriggerMeshResource =
            "TimeCliPistolTriggerMesh";
        public const string CannonMeshResource =
            "TimeCliCannonMesh";
        public const string LauncherMeshResource =
            "TimeCliLauncherMesh";

        public const string PistolTextureResource =
            "TimeCliPistolTexture";
        public const string CannonTextureResource =
            "TimeCliCannonTexture";
        public const string LauncherTextureResource =
            "TimeCliLauncherTexture";

        public const int PistolBaseVertexCount = 684;
        public const int PistolChamberOneVertexCount = 287;
        public const int PistolChamberTwoVertexCount = 287;
        public const int PistolTopVertexCount = 484;
        public const int PistolTriggerVertexCount = 60;
        public const int CannonVertexCount = 864;
        public const int LauncherVertexCount = 836;

        public static readonly Vector3 PistolBasePosition =
            new(
                0.00000000000000016f,
               -0.04195035249f,
               -0.08007901162f);

        public static readonly Vector3 PistolChamberOnePosition =
            new(
                0f,
                0.1756424606f,
                0f);

        public static readonly Vector3 PistolChamberTwoPosition =
            new(
                0f,
                0.09706403315f,
                0f);

        public static readonly Vector3 PistolTriggerPosition =
            new(
                0.000001369644451f,
               -0.007906286977f,
                0.02273671329f);

        public static readonly Color PistolColor =
            new(
                0f,
                0.4066853523f,
                1f,
                1f);

        public static readonly Color CannonColor =
            new(
                1f,
                0.8503905535f,
                0.4980391860f,
                1f);

        public static readonly Color LauncherColor =
            new(
                0.3286908865f,
                1f,
                0f,
                1f);
    }

    /// <summary>
    /// Adds private original-derived weapon meshes to the already reconstructed
    /// clean-room transform/animation hierarchy. When private resources are
    /// absent, compact clean fallback geometry is used instead.
    /// </summary>
    internal static class ClickWeaponVisualFactory
    {
        private static Material _pistolMaterial;
        private static Material _cannonMaterial;
        private static Material _launcherMaterial;

        public static void Populate(
            Transform pistolModel,
            Transform pistolTop,
            Transform cannonModel,
            Transform launcherModel)
        {
            if (pistolModel != null)
            {
                CreatePistolPart(
                    "base_and_grip",
                    pistolModel,
                    OriginalClickWeaponVisualPresentation.PistolBasePosition,
                    OriginalClickWeaponVisualPresentation.PistolBaseMeshResource,
                    "base_and_grip",
                    _ => GetPistolMaterial());

                CreatePistolPart(
                    "chamber_one",
                    pistolModel,
                    OriginalClickWeaponVisualPresentation.PistolChamberOnePosition,
                    OriginalClickWeaponVisualPresentation.PistolChamberOneMeshResource,
                    "chamber_one",
                    _ => GetPistolMaterial());

                CreatePistolPart(
                    "chamber_two",
                    pistolModel,
                    OriginalClickWeaponVisualPresentation.PistolChamberTwoPosition,
                    OriginalClickWeaponVisualPresentation.PistolChamberTwoMeshResource,
                    "chamber_two",
                    _ => GetPistolMaterial());

                CreatePistolPart(
                    "trigger",
                    pistolModel,
                    OriginalClickWeaponVisualPresentation.PistolTriggerPosition,
                    OriginalClickWeaponVisualPresentation.PistolTriggerMeshResource,
                    "trigger",
                    _ => GetPistolMaterial());
            }

            if (pistolTop != null)
            {
                AttachMeshOrFallback(
                    pistolTop,
                    OriginalClickWeaponVisualPresentation.PistolTopMeshResource,
                    "top1",
                    GetPistolMaterial(),
                    new Vector3(0.14f, 0.08f, 0.35f));
            }

            if (cannonModel != null)
            {
                AttachMeshOrFallback(
                    cannonModel,
                    OriginalClickWeaponVisualPresentation.CannonMeshResource,
                    "Plane_001",
                    GetCannonMaterial(),
                    new Vector3(0.22f, 0.22f, 0.55f));
            }

            if (launcherModel != null)
            {
                AttachMeshOrFallback(
                    launcherModel,
                    OriginalClickWeaponVisualPresentation.LauncherMeshResource,
                    "ClickLauncher",
                    GetLauncherMaterial(),
                    new Vector3(0.24f, 0.24f, 0.65f));
            }
        }

        private static void CreatePistolPart(
            string name,
            Transform parent,
            Vector3 localPosition,
            string meshResource,
            string meshName,
            System.Func<Transform, Material> materialFactory)
        {
            var part =
                new GameObject(name);

            part.transform.SetParent(
                parent,
                false);
            part.transform.localPosition =
                localPosition;
            part.transform.localRotation =
                new Quaternion(0f, 0f, 0f, 1f);
            part.transform.localScale =
                Vector3.one;

            AttachMeshOrFallback(
                part.transform,
                meshResource,
                meshName,
                materialFactory(part.transform),
                new Vector3(0.12f, 0.12f, 0.2f));
        }

        private static void AttachMeshOrFallback(
            Transform parent,
            string meshResource,
            string meshName,
            Material material,
            Vector3 fallbackScale)
        {
            Mesh mesh =
                PrivateProjectileObjMeshLoader.Load(
                    meshResource,
                    meshName);

            if (mesh != null)
            {
                var visual =
                    new GameObject(
                        meshName + "_Visual");

                visual.transform.SetParent(
                    parent,
                    false);
                visual.transform.localPosition =
                    Vector3.zero;
                visual.transform.localRotation =
                    new Quaternion(0f, 0f, 0f, 1f);
                visual.transform.localScale =
                    Vector3.one;

                MeshFilter filter =
                    visual.AddComponent<MeshFilter>();
                MeshRenderer renderer =
                    visual.AddComponent<MeshRenderer>();

                filter.sharedMesh = mesh;
                renderer.sharedMaterial = material;
                return;
            }

            GameObject fallback =
                GameObject.CreatePrimitive(
                    PrimitiveType.Cube);

            fallback.name =
                meshName + "_CleanFallback";
            fallback.transform.SetParent(
                parent,
                false);
            fallback.transform.localPosition =
                Vector3.zero;
            fallback.transform.localRotation =
                new Quaternion(0f, 0f, 0f, 1f);
            fallback.transform.localScale =
                fallbackScale;

            Collider collider =
                fallback.GetComponent<Collider>();
            if (collider != null)
                UnityEngine.Object.Destroy(collider);

            Renderer renderer =
                fallback.GetComponent<Renderer>();
            if (renderer != null)
                renderer.sharedMaterial = material;
        }

        private static Material GetPistolMaterial()
        {
            if (_pistolMaterial == null)
            {
                _pistolMaterial =
                    BuildWeaponMaterial(
                        "TimeCli_Reconstructed_PulsePistol",
                        OriginalClickWeaponVisualPresentation.PistolColor,
                        OriginalClickWeaponVisualPresentation.PistolTextureResource);
            }

            return _pistolMaterial;
        }

        private static Material GetCannonMaterial()
        {
            if (_cannonMaterial == null)
            {
                _cannonMaterial =
                    BuildWeaponMaterial(
                        "TimeCli_Reconstructed_ClickCannon",
                        OriginalClickWeaponVisualPresentation.CannonColor,
                        OriginalClickWeaponVisualPresentation.CannonTextureResource);
            }

            return _cannonMaterial;
        }

        private static Material GetLauncherMaterial()
        {
            if (_launcherMaterial == null)
            {
                _launcherMaterial =
                    BuildWeaponMaterial(
                        "TimeCli_Reconstructed_ClickLauncher",
                        OriginalClickWeaponVisualPresentation.LauncherColor,
                        OriginalClickWeaponVisualPresentation.LauncherTextureResource);
            }

            return _launcherMaterial;
        }

        private static Material BuildWeaponMaterial(
            string name,
            Color color,
            string textureResource)
        {
            Shader shader =
                Shader.Find(
                    "TimeCli/WeaponDiffuseColor");

            if (shader == null)
                shader = Shader.Find("Unlit/Texture");

            var material =
                new Material(shader)
                {
                    name = name,
                    color = color
                };

            Texture2D texture =
                Resources.Load<Texture2D>(
                    textureResource);

            if (texture != null)
            {
                texture.filterMode =
                    FilterMode.Bilinear;
                texture.wrapMode =
                    TextureWrapMode.Repeat;
                texture.anisoLevel = 1;
                material.mainTexture =
                    texture;
            }

            return material;
        }
    }
}
